# Generated by Django 5.1.2 on 2025-12-19 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOCConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_window_minutes', models.PositiveIntegerField(default=15)),
                ('threshold_low', models.PositiveIntegerField(default=5)),
                ('threshold_medium', models.PositiveIntegerField(default=3)),
                ('threshold_high', models.PositiveIntegerField(default=2)),
                ('threshold_critical', models.PositiveIntegerField(default=1)),
                ('enable_brute_force', models.BooleanField(default=True)),
                ('enable_scanning', models.BooleanField(default=True)),
                ('enable_unauthorized_access', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SOC Configuration',
                'verbose_name_plural': 'SOC Configuration',
            },
        ),
        migrations.CreateModel(
            name='AnalystProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
