# Generated by Django 4.2.27 on 2025-12-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soc_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelatedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=32)),
                ('source', models.CharField(help_text='Log source or asset associated with this event.', max_length=128)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_alerts', models.PositiveIntegerField()),
                ('risk_score', models.FloatField(help_text='Calculated risk score based on severity and volume.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_promoted_to_incident', models.BooleanField(default=False)),
                ('related_alerts', models.ManyToManyField(blank=True, related_name='correlated_events', to='soc_analyzer.rawalertanalysis')),
            ],
            options={
                'verbose_name': 'Correlated Event',
                'verbose_name_plural': 'Correlated Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
