# Generated by Django 4.2.27 on 2025-12-19 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soc_correlation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(help_text='Unique incident identifier (e.g., INC-2025-001)', max_length=32, unique=True)),
                ('attack_type', models.CharField(help_text='Type of attack detected.', max_length=32)),
                ('risk_score', models.FloatField(help_text='Risk score inherited from correlated event.')),
                ('current_status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('mitigated', 'Mitigated'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='SOC analyst assigned to investigate this incident.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('correlated_event', models.OneToOneField(help_text='The correlated security event this incident was created from.', on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='soc_correlation.correlatedevent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_status', models.CharField(blank=True, help_text='Previous status before change.', max_length=16)),
                ('new_status', models.CharField(help_text='New status after change.', max_length=16)),
                ('notes', models.TextField(help_text='Investigation notes or reason for status change.')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_history_entries', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='soc_incidents.incident')),
            ],
            options={
                'verbose_name': 'Incident History Entry',
                'verbose_name_plural': 'Incident History Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
