# Generated by Django 5.1.2 on 2025-12-19 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('log_upload', 'Log upload'), ('manual_log_entry', 'Manual log entry'), ('incident_update', 'Incident update'), ('incident_create', 'Incident create')], max_length=32)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('related_type', models.CharField(blank=True, max_length=64)),
                ('related_id', models.CharField(blank=True, max_length=128)),
                ('sequence_number', models.BigIntegerField()),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-sequence_number'],
            },
        ),
    ]
