# Generated by Django 5.1.2 on 2025-12-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('log_upload', 'Log upload'), ('manual_log_entry', 'Manual log entry'), ('incident_update', 'Incident update'), ('incident_create', 'Incident create'), ('admin_user_create', 'Admin user create'), ('admin_user_update', 'Admin user update'), ('admin_user_password_reset', 'Admin user password reset'), ('admin_config_update', 'Admin config update')], max_length=32),
        ),
    ]
