# Generated by Django 4.2.27 on 2025-12-19 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('log_source', models.CharField(max_length=128)),
                ('raw_message', models.TextField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingested_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raw Log Entry',
                'verbose_name_plural': 'Raw Log Entries',
                'ordering': ['-ingested_at'],
            },
        ),
    ]
