# Generated by Django 4.2.27 on 2025-12-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlogentry',
            name='processing_status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processed', 'Processed')], default='unprocessed', help_text='Processing lifecycle state of this raw alert.', max_length=16),
        ),
    ]
