# Generated by Django 4.2.27 on 2025-12-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soc_ingest', '0002_rawlogentry_processing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawAlertAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('attack_type', models.CharField(choices=[('brute_force', 'Brute-force login'), ('account_enum', 'Account enumeration'), ('web_scanning', 'Web scanning'), ('unauthorized_access', 'Unauthorized access'), ('unknown', 'Unknown / benign')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('rule_name', models.CharField(help_text='Name of the detection rule that matched.', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('raw_alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='soc_ingest.rawlogentry')),
            ],
            options={
                'verbose_name': 'Raw Alert Analysis',
                'verbose_name_plural': 'Raw Alert Analyses',
                'ordering': ['-detected_at'],
            },
        ),
    ]
